name: pr-security-review

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.png'
      - '**/*.jpg'
      - '.github/branch-protection/**'

permissions:
  contents: read
  checks: write
  pull-requests: write
  security-events: write

concurrency:
  group: pr-security-review-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  robin-sec:
    name: Robin Sec            # <-- keep this EXACT to match your required check
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0        # full history for reliable diffing

      - name: Ensure base ref is present locally
        run: |
          BASE="${{ github.base_ref || 'main' }}"
          git fetch origin "$BASE:$BASE" --update-head-ok || true
          git branch -vv

      - name: Cache Semgrep rules
        uses: actions/cache@v4
        with:
          path: ~/.semgrep
          key: semgrep-${{ runner.os }}-v1

      - name: Install Semgrep
        run: pipx install semgrep

      - name: Semgrep (delta with safety limits)
        id: scan
        shell: bash
        run: |
          set -euo pipefail
          BASE="${{ github.base_ref || 'main' }}"

          if semgrep --help | grep -q -- '--changed-since'; then
            semgrep scan \
              --config rules/ \
              --config p/security-audit \
              --config p/secrets \
              --changed-since "$BASE" \
              --exclude node_modules --exclude dist --exclude .git \
              --max-target-bytes 200MB \
              --timeout 300 \
              --error --jobs auto \
              --sarif --output results.sarif
          else
            MERGE_BASE="$(git merge-base HEAD "$BASE")"
            semgrep scan \
              --config rules/ \
              --config p/security-audit \
              --config p/secrets \
              --baseline-commit "$MERGE_BASE" \
              --exclude node_modules --exclude dist --exclude .git \
              --max-target-bytes 200MB \
              --timeout 300 \
              --error --jobs auto \
              --sarif --output results.sarif
          fi

      - name: Upload SARIF to Code Scanning
        if: always() && hashFiles('results.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
