name: pr-security-review

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
    branches: [main]                # limit to PRs targeting main (adjust if needed)
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.png'
      - '**/*.jpg'
      - '.github/branch-protection/**'

permissions:
  contents: read
  checks: write
  pull-requests: write
  security-events: write

concurrency:
  group: pr-security-review-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0             # needed for diff/baseline

      - name: Cache Semgrep rules
        uses: actions/cache@v4
        with:
          path: ~/.semgrep
          key: semgrep-${{ runner.os }}-v1

      - name: Install Semgrep
        run: pipx install semgrep

      # Use delta scan where supported; fall back to baseline filtering otherwise
      - name: Semgrep (delta with safety limits)
        id: scan
        shell: bash
        run: |
          set -euo pipefail
          BASE="${{ github.base_ref }}"
          [[ -z "$BASE" ]] && BASE=main

          # Prefer delta scanning (Semgrep >= 1.39 supports --changed-since)
          if semgrep --help | grep -q -- '--changed-since'; then
            semgrep scan \
              --config rules/ \
              --config p/security-audit \
              --config p/secrets \
              --changed-since "origin/$BASE" \
              --exclude node_modules --exclude dist --exclude .git \
              --max-target-bytes 200MB \
              --timeout 300 \
              --error --jobs auto \
              --sarif --output results.sarif
          else
            # Fallback: scan all but only report findings introduced since merge-base
            MERGE_BASE="$(git merge-base HEAD "origin/$BASE")"
            semgrep scan \
              --config rules/ \
              --config p/security-audit \
              --config p/secrets \
              --baseline-commit "$MERGE_BASE" \
              --exclude node_modules --exclude dist --exclude .git \
              --max-target-bytes 200MB \
              --timeout 300 \
              --error --jobs auto \
              --sarif --output results.sarif
          fi

      # Upload SARIF via the supported action (no reliance on gh being present)
      - name: Upload SARIF to Code Scanning
        if: always() && hashFiles('results.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
