rules:
  - id: py.dangerous.eval
    message: "Use of eval is unsafe."
    severity: ERROR
    languages: [python]
    pattern: eval(...)

  - id: py.subprocess.shell-true
    message: "subprocess with shell=True can enable command injection."
    severity: ERROR
    languages: [python]
    pattern-either:
      - pattern: subprocess.run(..., shell=True, ...)
      - pattern: subprocess.Popen(..., shell=True, ...)
      - pattern: subprocess.call(..., shell=True, ...)
      - pattern: subprocess.check_call(..., shell=True, ...)
      - pattern: subprocess.check_output(..., shell=True, ...)
      - pattern: os.system(...)

  - id: py.weak-hash.md5
    message: "MD5 is cryptographically broken; use SHA-256 or better."
    severity: WARNING
    languages: [python]
    pattern: hashlib.md5(...)

  - id: py.yaml.unsafe-load
    message: "yaml.load without SafeLoader is unsafe; use yaml.safe_load."
    severity: ERROR
    languages: [python]
    patterns:
      - pattern: yaml.load(...)
      - pattern-not: yaml.load(..., Loader=yaml.SafeLoader)
      - pattern-not: yaml.load(..., Loader=SafeLoader)

  - id: py.pickle.loads
    message: "Insecure deserialization with pickle.loads."
    severity: ERROR
    languages: [python]
    pattern: pickle.loads(...)

  - id: py.requests.verify-disabled
    message: "TLS verification disabled; avoid verify=False."
    severity: WARNING
    languages: [python]
    pattern-either:
      - pattern: requests.get(..., verify=False, ...)
      - pattern: requests.post(..., verify=False, ...)
      - pattern: requests.put(..., verify=False, ...)
      - pattern: requests.delete(..., verify=False, ...)
      - pattern: requests.request(..., verify=False, ...)

  - id: py.tempfile.mktemp
    message: "tempfile.mktemp() is unsafe (race condition). Use NamedTemporaryFile or mkstemp."
    severity: WARNING
    languages: [python]
    pattern: tempfile.mktemp(...)

  - id: py.random.insecure-for-secrets
    message: "random.* is not cryptographically secure. Use secrets.token_urlsafe / os.urandom."
    severity: WARNING
    languages: [python]
    pattern-either:
      - pattern: random.random(...)
      - pattern: random.randint(...)
      - pattern: random.randrange(...)
      - pattern: random.choice(...)
      - pattern: random.getrandbits(...)
      - pattern: random.uniform(...)
      - pattern: random.shuffle(...)

  - id: py.tarfile.extractall.path-traversal
    message: "tarfile.extractall() may allow path traversal; validate members first."
    severity: ERROR
    languages: [python]
    pattern-either:
      - pattern: tarfile.extractall(...)
      - pattern: tarfile.open(...).extractall(...)
      - pattern: |
          with tarfile.open(...) as $TF:
            ...
            $TF.extractall(...)
