name: RobinSec

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.png'
      - '**/*.jpg'
      - '.github/branch-protection/**'

permissions:
  contents: read
  checks: write
  pull-requests: write
  security-events: write

concurrency:
  group: robinsec-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  RobinSec:
    name: RobinSec
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Semgrep
        run: pipx install semgrep

      - name: Semgrep (PR-aware)
        run: |
          semgrep ci \
            --config rules/rules.yaml \
            --config p/security-audit \
            --config p/secrets \
            --timeout 300 \
            --max-target-bytes 200MB \
            --sarif --output results.sarif

      - name: Upload SARIF to Security tab
        if: always() && hashFiles('results.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
